name: encrypt
version: 1.0.0+1
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pointycastle:
      git:
      url: https://github.com/bbedward/pointycastle.git
      ref: master

dev_dependencies:
  test: ^1.5.1+1
